version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tlakshan470/hello-world:latest
    container_name: hello-world
    ports:
      - "8085:8085"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge